'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { getCurrentUser } from '@/lib/supabase/auth';
import { upsertStudentProfile } from '@/lib/supabase/database';
import SignOutButton from '@/components/auth/SignOutButton';

export default function OnboardingPage() {
  const router = useRouter(); const [userId, setUserId] = useState(''); const [email, setEmail] = useState('');
  const [form, setForm] = useState({ full_name: '', major: '', interests: '', career_goals: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { getCurrentUser().then((user) => { if (!user) router.replace('/login'); else { setUserId(user.id); setEmail(user.email ?? ''); } }); }, [router]);
  function update(field: keyof typeof form, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); setSaving(true); const { error: saveError } = await upsertStudentProfile(userId, { ...form, email, interests: form.interests.split(',').map((item) => item.trim()) }); if (saveError) setError(saveError.message); else router.replace('/dashboard'); setSaving(false); }
  return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6"><div className="mx-auto max-w-3xl"><header className="mb-8 flex items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-brand-700">Student onboarding</p><h1 className="mt-2 text-3xl font-black text-slate-900 sm:text-4xl">Build your career profile</h1><p className="mt-2 text-slate-600">Your answers power better recommendations.</p></div><SignOutButton /></header><form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-soft sm:p-8">{error && <p role="alert" className="mb-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Full name<input required value={form.full_name} onChange={(e) => update('full_name', e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-brand-500" /></label><label className="text-sm font-semibold text-slate-700">Email<input disabled value={email} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-100 px-4 py-3 font-normal text-slate-500" /></label><label className="text-sm font-semibold text-slate-700">Major or field of study<input required value={form.major} onChange={(e) => update('major', e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-brand-500" /></label><label className="text-sm font-semibold text-slate-700">Career interests<input value={form.interests} onChange={(e) => update('interests', e.target.value)} placeholder="Design, data, product" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-brand-500" /></label></div><label className="mt-5 block text-sm font-semibold text-slate-700">Career goals<textarea required rows={5} value={form.career_goals} onChange={(e) => update('career_goals', e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-brand-500" /></label><button disabled={saving} className="mt-6 w-full rounded-xl bg-brand-600 px-5 py-3 font-semibold text-white hover:bg-brand-700 disabled:opacity-50">{saving ? 'Saving profile…' : 'Save and view dashboard'}</button></form></div></main>;
}
