'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { getCurrentUser } from '@/lib/supabase/auth';
import { getDashboardData } from '@/lib/supabase/database';
import SignOutButton from '@/components/auth/SignOutButton';

type Row = { id: string; role_name?: string; fit_score?: number; reason?: string; milestone?: string; status?: string; due_date?: string };
export default function DashboardPage() {
  const router = useRouter(); const [profile, setProfile] = useState<any>(null); const [recommendations, setRecommendations] = useState<Row[]>([]); const [progress, setProgress] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { (async () => { const user = await getCurrentUser(); if (!user) { router.replace('/login'); return; } const data = await getDashboardData(user.id); if (data.profile.error) { setError(data.profile.error.message); } else { setProfile(data.profile.data); setRecommendations(data.recommendations.data ?? []); setProgress(data.progress.data ?? []); } setLoading(false); })(); }, [router]);
  if (loading) return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-6xl animate-pulse space-y-6"><div className="h-12 w-64 rounded bg-slate-200" /><div className="grid gap-5 sm:grid-cols-3"><div className="h-32 rounded-2xl bg-slate-200" /><div className="h-32 rounded-2xl bg-slate-200" /><div className="h-32 rounded-2xl bg-slate-200" /></div></div></main>;
  if (error) return <main className="p-6"><p role="alert" className="mx-auto max-w-2xl rounded-xl bg-red-50 p-4 text-red-700">{error}</p></main>;
  const completed = progress.filter((item) => item.status === 'completed').length;
  return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6"><div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-widest text-brand-700">Student dashboard</p><h1 className="mt-2 text-3xl font-black text-slate-900 sm:text-4xl">Welcome, {profile?.full_name ?? 'student'}.</h1><p className="mt-2 text-slate-600">{profile?.major} {profile?.interests?.length ? `• ${profile.interests.join(', ')}` : ''}</p></div><SignOutButton /></header><section className="grid gap-5 sm:grid-cols-3"><article className="rounded-2xl bg-white p-6 shadow-soft"><p className="text-sm text-slate-500">Top career fit</p><p className="mt-2 text-4xl font-black text-brand-600">{recommendations[0] ? Math.round((recommendations[0].fit_score ?? 0) * 100) : 0}%</p></article><article className="rounded-2xl bg-white p-6 shadow-soft"><p className="text-sm text-slate-500">Milestones complete</p><p className="mt-2 text-4xl font-black text-emerald-600">{completed}/{progress.length}</p></article><article className="rounded-2xl bg-white p-6 shadow-soft"><p className="text-sm text-slate-500">Recommended paths</p><p className="mt-2 text-4xl font-black text-slate-900">{recommendations.length}</p></article></section><div className="mt-8 grid gap-8 lg:grid-cols-[1.5fr_1fr]"><section><h2 className="text-2xl font-bold text-slate-900">Career recommendations</h2><div className="mt-4 space-y-4">{recommendations.length ? recommendations.map((item) => <article key={item.id} className="rounded-2xl bg-white p-5 shadow-soft"><div className="flex items-start justify-between gap-4"><div><h3 className="font-bold text-slate-900">{item.role_name}</h3><p className="mt-2 text-sm text-slate-600">{item.reason}</p></div><span className="rounded-full bg-brand-50 px-3 py-1 text-sm font-bold text-brand-700">{Math.round((item.fit_score ?? 0) * 100)}%</span></div></article>) : <p className="rounded-2xl bg-white p-6 text-slate-600 shadow-soft">Recommendations will appear after your profile is analyzed.</p>}</div></section><section><h2 className="text-2xl font-bold text-slate-900">Your milestones</h2><div className="mt-4 space-y-3">{progress.length ? progress.map((item) => <article key={item.id} className="rounded-2xl bg-white p-4 shadow-soft"><p className="font-semibold text-slate-900">{item.milestone}</p><p className="mt-1 text-sm capitalize text-slate-500">{item.status}{item.due_date ? ` • due ${new Date(item.due_date).toLocaleDateString()}` : ''}</p></article>) : <p className="rounded-2xl bg-white p-6 text-slate-600 shadow-soft">No milestones yet.</p>}</div></section></div></div></main>;
}
